%YAML:1.0

Camera.type: "PinHole"

Camera.fx: 1453.72
Camera.fy: 1453.28
Camera.cx: 1172.18
Camera.cy: 1041.78

Camera.k1: -0.1210
Camera.k2: 0.1113
Camera.p1: 0.0016
Camera.p2: 0.00013
Camera.k3: -0.062353

Camera.width: 2448
Camera.height: 2048

Camera.fps: 10.0
Camera.RGB: 0

ORBextractor.nFeatures: 3500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

Viewer.UseViewer: 0

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0